Ajout des tests automatisés
dd701116/esgi-nodejs-projet pull request #20
Opened 2021-03-29 08:23 UTC by TOomaAh

2021-03-29 12:07 UTC, antoineThiel submitted a review, later dismissed

2021-03-29 14:13 UTC, dd701116 requested changes
Comme tu l'as dit sur discord, il te manque les variables d'environnement et surtout, il faut penser à monter une base de données dans le conteneur pour les tests.
La création de la base de données, ça pourrait être un jobs, à voir...

2021-03-29 14:13 UTC, dd701116 commented on .github/workflows/node.js.yml
> +  build:
Il faut renommer le job en "tests"

2021-03-29 14:13 UTC, dd701116 commented on .github/workflows/node.js.yml
> +    - run: npm run build --if-present
hmm, nope, pas pour les tests, il faudrait faire un job spécial pour le build.
Aussi, on a rien à build pour le moment, du coup c'est pas nécessaire.

2021-03-29 14:22 UTC, dd701116 commented on .github/workflows/node.js.yml
> +        npm start &
Il ne faut pas lancer le serveur, le github action va tourner indéfiniment. Il faut juste lancer les tests comme tu as fait par la suite 👍

2021-03-29 14:23 UTC, dd701116 commented on .github/workflows/node.js.yml
> +        npx wait-on http://localhost:8000
hmm, je suis pas certain.

2021-04-03 13:57 UTC, dd701116 approved these changes

2021-04-04 21:47 UTC, lucc70 approved these changes

2021-04-05 10:32 UTC, antoineThiel approved these changes

2021-04-05 10:32 UTC, merged