Route put/patch note
dd701116/esgi-nodejs-projet pull request #23
Opened 2021-04-04 17:02 UTC by antoineThiel

2021-04-04 17:05 UTC, TOomaAh approved these changes

2021-04-05 10:41 UTC, dd701116 requested changes
C'est parfait, juste quelque truc à ajuster.
Ah oui, une SEUL tache par pull request !
La je vois déjà 2 taches qui sont en train de se faire dans cette pull request et vu le titre, il y en aura une 3 ème.
Je ne validerais jamais cette pull request.

2021-04-05 10:41 UTC, dd701116 commented on test/note.test.js
> +});
Saute une ligne à la fin du fichier, après c'est parfait, vous êtes génial !

2021-04-05 10:41 UTC, dd701116 commented on server.js
> +require('./routes/note.route')(fastify);
Il faut mettre le require tout en haut et faire appel à la constante à ce niveau là.
Trop de saut de ligne, si on fait passer ESLint dessus, la console va pleurer.

2021-04-05 10:41 UTC, dd701116 commented on routes/note.route.js
> +}
Saut de ligne en fin de fichier

2021-04-06 11:41 UTC, closed without merging